#!/usr/bin/env python
# coding: utf-8
from __future__ import print_function, unicode_literals
import getopt
import sys
from bdy.baiduyun import BaiduYun
from bdy import utils

if __name__ == "__main__":
    oauth_info = utils.read_oauth_info()
    opts, args = getopt.getopt(sys.argv[1:], "hb")
    if not utils.oauth_check(oauth_info):
        client_id = utils.get_config("apikey")
        oa_url = "http://openapi.baidu.com/oauth/2.0/authorize?client_id={client_id}" \
                 "&response_type=token&redirect_uri=oob" \
                 "&scope=netdisk".format(client_id=client_id)
        oa_result_base = utils.get_config("oa_result")
        for op, va in opts:
            if "-b" in op:
                from bdy import oauth_browser
                oauth_result = oauth_browser.get_oa_info(oa_url, oa_result_base)
            else:
                from bdy import oauth_ui
                oauth_result = oauth_ui.get_oa_info(oa_url, oa_result_base)
        oauth_info = utils.get_oauth_result(oauth_result)
        if not utils.oauth_check(oauth_info):
            print(oauth_info)
            print("登录错误")
            exit()
        utils.save_oauth_info(oauth_info)

    print("获取数据成功")
    bdy = BaiduYun(oauth_info)
    try:
        utils.menu(bdy)
    except Exception:
        exit()